import Head from 'next/head'
import Image from 'next/image'
import {Button} from '@@yum'
import { useEffect } from 'react';

/*
<script charset="utf-8" type="text/javascript" src="//js-eu1.hsforms.net/forms/shell.js"></script>
<script>
  hbspt.forms.create({
	region: "eu1",
	portalId: "25408596",
	formId: "c72ae9a0-25c5-4f62-be94-d62633802d3e"
});
</script>
*/

export default function Home() {
  useEffect(() => {
    const script = document.createElement('script');
    script.src='//js-eu1.hsforms.net/forms/shell.js';
    document.body.appendChild(script);

    script.addEventListener('load', () => {
        if (window.hbspt) {
            window.hbspt.forms.create({
              region: "eu1",
              portalId: "25408596",
              formId: "c72ae9a0-25c5-4f62-be94-d62633802d3e",
              target: '#custom-form1'
            })
        }
    });
  }, []);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <Button></Button>

        <div id="custom-form1"></div>
      </main>

    </div>
  )
}
